# Pytorch Basics

In [262]:
# Most of the examples are from the documentation but with some additions and comments
# https://pytorch.org/tutorials/index.html

import torch
import torchvision
#check which version you are using.
print torch.__version__

0.4.0


# Construct a tensor

In [263]:
print('If dtype is not specified while creating a tensor, it defaults to float32')
w = torch.empty((3,3))  # Un-initialized - contains junk values
print w
print('\n*** For floating point values, if dtype is not mentioned in output as above, it is float32 by default. ')
print w.dtype

Wf dtype is not specified while creating a tensor, it defaults to float32
tensor(1.00000e-11 *
       [[ 0.0000,  0.0000,  0.0000],
        [ 0.0000,  5.0122,  0.0000],
        [ 0.0000,  0.0000,  0.0000]])

*** For floating point values, if dtype is not mentioned in output as above, it is float32 by default. 
torch.float32


In [264]:
y = torch.rand((3,3), dtype = torch.float64)   # random values
print 'If a floating point tensor is not of default type(float32), it gets displayed while printing'
print y

If a floating point tensor is not of default type(float32), it gets displayed while printing
tensor([[ 0.0119,  0.7231,  0.3239],
        [ 0.6263,  0.4370,  0.1674],
        [ 0.6706,  0.0675,  0.3328]], dtype=torch.float64)


In [265]:
x = torch.zeros((3,3), dtype = torch.long)     # Initialized to zeros
print x
print('*** For non floating point, if dtype is not mentioned in output as above, default is long(int64)')
print x.dtype

tensor([[ 0,  0,  0],
        [ 0,  0,  0],
        [ 0,  0,  0]])
*** For non floating point, if dtype is not mentioned in output as above, default is long(int64)
torch.int64


In [266]:
z = torch.empty((3,3), dtype = torch.int32)    # Un-initialized values
print 'If a integer tensor is not of default type(int64), it gets displayed while printing'
print z 

If a integer tensor is not of default type(int64), it gets displayed while printing
tensor([[-1.7186e+09,  3.2610e+04,  5.2245e+07],
        [ 0.0000e+00,  2.5362e+07,  2.1965e+05],
        [ 1.3925e+09,  4.0108e+07,  4.8000e+01]], dtype=torch.int32)


# Construct tensor from data

In [267]:
#Construct tensor from data
y = np.asarray([[0.5, 0.2],[0.7,2]], dtype=np.float64) # this is float 64
print '\ny is a numpy array'
print y
print 'y.dtype:', y.dtype



y is a numpy array
[[0.5 0.2]
 [0.7 2. ]]
y.dtype: float64


In [268]:
w = torch.from_numpy(y) 
print '\nCreate a tensor w from y directly'
print w
print 'w.dtype:', w.dtype


Create a tensor w from y directly
tensor([[ 0.5000,  0.2000],
        [ 0.7000,  2.0000]], dtype=torch.float64)
w.dtype: torch.float64


In [269]:
x = torch.IntTensor(y) # We converted to Int
print '\nCreate x from y but by changing type'
print x
print 'x.dtype:', x.dtype


Create x from y but by changing type
tensor([[ 0,  0],
        [ 0,  2]], dtype=torch.int32)
x.dtype: torch.int32


In [270]:
x = torch.DoubleTensor([[0.5, 0.2],[0.7,2]])
print '\nCreating a double tensor directly'
print x
print 'x.dtype:', x.dtype


Creating a double tensor directly
tensor([[ 0.5000,  0.2000],
        [ 0.7000,  2.0000]], dtype=torch.float64)
x.dtype: torch.float64


# Indexing and reshaping

In [271]:
#Indexing similar to python
x = torch.rand((4,4))
print x

tensor([[ 0.8265,  0.0990,  0.9314,  0.8799],
        [ 0.7774,  0.4609,  0.4119,  0.7068],
        [ 0.6018,  0.6430,  0.8177,  0.4626],
        [ 0.8928,  0.2464,  0.7398,  0.4523]])


In [272]:
print x[:,1]

tensor([ 0.0990,  0.4609,  0.6430,  0.2464])


In [273]:
print x[1:3,1:3]

tensor([[ 0.4609,  0.4119],
        [ 0.6430,  0.8177]])


In [274]:
print x[3,3]
print x[-1,-1]

tensor(0.4523)
tensor(0.4523)


In [289]:
# Masking 
x = torch.rand((5,5))
print x
x[x<0.5] = 0
print x

tensor([[ 0.6002,  0.3685,  0.3732,  0.8921,  0.9191],
        [ 0.1576,  0.0544,  0.6254,  0.5700,  0.6490],
        [ 0.1190,  0.6315,  0.7381,  0.2133,  0.7262],
        [ 0.1653,  0.2217,  0.1558,  0.3401,  0.4882],
        [ 0.7140,  0.7675,  0.1313,  0.3967,  0.3951]])
tensor([[ 0.6002,  0.0000,  0.0000,  0.8921,  0.9191],
        [ 0.0000,  0.0000,  0.6254,  0.5700,  0.6490],
        [ 0.0000,  0.6315,  0.7381,  0.0000,  0.7262],
        [ 0.0000,  0.0000,  0.0000,  0.0000,  0.0000],
        [ 0.7140,  0.7675,  0.0000,  0.0000,  0.0000]])


In [275]:
#Resizing and reshaping tensor
print x
print 'x:', x.size()

tensor([[ 0.8265,  0.0990,  0.9314,  0.8799],
        [ 0.7774,  0.4609,  0.4119,  0.7068],
        [ 0.6018,  0.6430,  0.8177,  0.4626],
        [ 0.8928,  0.2464,  0.7398,  0.4523]])
x: torch.Size([4, 4])


In [276]:
y = x.view((2,2,2,2))
print y
print 'y:', y.size()

tensor([[[[ 0.8265,  0.0990],
          [ 0.9314,  0.8799]],

         [[ 0.7774,  0.4609],
          [ 0.4119,  0.7068]]],


        [[[ 0.6018,  0.6430],
          [ 0.8177,  0.4626]],

         [[ 0.8928,  0.2464],
          [ 0.7398,  0.4523]]]])
y: torch.Size([2, 2, 2, 2])


In [277]:
z = x.view((-1,8))
print z
print 'z:', z.size()

tensor([[ 0.8265,  0.0990,  0.9314,  0.8799,  0.7774,  0.4609,  0.4119,
          0.7068],
        [ 0.6018,  0.6430,  0.8177,  0.4626,  0.8928,  0.2464,  0.7398,
          0.4523]])
z: torch.Size([2, 8])


# Broadcasting 

In [298]:
# Two tensors are “broadcastable” if the following rules hold:
#       1. Each tensor has at least one dimension.
#       2. When iterating over the dimension sizes, starting at the trailing dimension, 
#           the dimension sizes must either be equal, one of them is 1, or one of them does not exist.

x = torch.rand(2,4,3)
y = torch.rand(2,4,3)
z = x + y
print '***same shapes are always broadcastable'
print('x.size(): ', x.size())
print('y.size(): ', y.size())
print('z.size(): ', z.size())
print '\n\n'
print x
print y
print z

***same shapes are always broadcastable
('x.size(): ', torch.Size([2, 4, 3]))
('y.size(): ', torch.Size([2, 4, 3]))
('z.size(): ', torch.Size([2, 4, 3]))



tensor([[[ 0.2801,  0.6681,  0.8727],
         [ 0.8908,  0.3821,  0.0236],
         [ 0.4907,  0.0632,  0.3685],
         [ 0.4588,  0.6855,  0.1147]],

        [[ 0.4200,  0.2966,  0.4891],
         [ 0.9992,  0.1163,  0.0473],
         [ 0.0871,  0.4790,  0.4528],
         [ 0.5797,  0.3806,  0.8701]]])
tensor([[[ 0.8422,  0.6807,  0.3745],
         [ 0.8817,  0.4352,  0.3723],
         [ 0.5443,  0.1888,  0.8803],
         [ 0.7200,  0.1064,  0.7601]],

        [[ 0.1864,  0.3114,  0.2718],
         [ 0.5344,  0.6641,  0.5338],
         [ 0.1954,  0.0441,  0.1457],
         [ 0.5033,  0.3010,  0.5601]]])
tensor([[[ 1.1223,  1.3488,  1.2472],
         [ 1.7725,  0.8173,  0.3959],
         [ 1.0349,  0.2520,  1.2488],
         [ 1.1788,  0.7919,  0.8748]],

        [[ 0.6064,  0.6080,  0.7609],
         [ 1.5336,  0.7805,  0.5811

In [303]:
x = torch.empty((0,))
y = torch.empty(2,2)

print '***x and y are not broadcastable, because x does not have at least 1 dimension'
print('x.size(): ', x.size())
print('y.size(): ', y.size())

print x
print y

# z = x + y
# print('z.size(): ', z.size())
# print '\n\n'
# print z
print '*** TODO: uncomment the lines and you will get error'

***x and y are not broadcastable, because x does not have at least 1 dimension
('x.size(): ', torch.Size([0]))
('y.size(): ', torch.Size([2, 2]))
tensor([])
tensor(1.00000e-23 *
       [[-1.4866,  0.0000],
        [ 0.0000,  0.0000]])
*** TODO: uncomment the lines and you will get error


In [315]:
x = torch.rand(  3,1,2)
y = torch.rand(2,3,4,2)
z = x + y
print '*** x and y are broadcastable:'
print '       1st trailing dimension: x size == y size'
print '       2nd trailing dimension: x has size 1'
print '       3rd trailing dimension: x size == y size'
print "       4th trailing dimension: x dimension doesn't exist"
print '\n'
print('x.size(): ', x.size())
print('y.size(): ', y.size())
print('z.size(): ', z.size())
print '\n\n'
print x
print y
print z

*** x and y are broadcastable:
       1st trailing dimension: x size == y size
       2nd trailing dimension: x has size 1
       3rd trailing dimension: x size == y size
       4th trailing dimension: x dimension doesn't exist


('x.size(): ', torch.Size([3, 1, 2]))
('y.size(): ', torch.Size([2, 3, 4, 2]))
('z.size(): ', torch.Size([2, 3, 4, 2]))



tensor([[[ 0.5311,  0.7328]],

        [[ 0.8943,  0.6699]],

        [[ 0.2537,  0.5200]]])
tensor([[[[ 0.0524,  0.5522],
          [ 0.2590,  0.9951],
          [ 0.8173,  0.7871],
          [ 0.3239,  0.7897]],

         [[ 0.8344,  0.2681],
          [ 0.4990,  0.9582],
          [ 0.4239,  0.5703],
          [ 0.9591,  0.1306]],

         [[ 0.2504,  0.4479],
          [ 0.1704,  0.3618],
          [ 0.6148,  0.5104],
          [ 0.1540,  0.0082]]],


        [[[ 0.7353,  0.3530],
          [ 0.6292,  0.9270],
          [ 0.2401,  0.5074],
          [ 0.1833,  0.9220]],

         [[ 0.1890,  0.4441],
          [ 0.4173,  0.4655],
    

In [312]:
x=torch.rand(2,3,4,1)
y=torch.rand(  2,1,1)
print 'x and y are not broadcastable, because in the 3rd trailing dimension 3 != 2'
print('x.size(): ', x.size())
print('y.size(): ', y.size())

print x
print y

# z = x + y
# print('z.size(): ', z.size())
# print '\n\n'
# print z
print '*** TODO: uncomment the lines and you will get error'

x and y are not broadcastable, because in the 3rd trailing dimension 2 != 3
('x.size(): ', torch.Size([2, 3, 4, 1]))
('y.size(): ', torch.Size([2, 1, 1]))
tensor([[[[ 0.5055],
          [ 0.5379],
          [ 0.6831],
          [ 0.6969]],

         [[ 0.7824],
          [ 0.9815],
          [ 0.6182],
          [ 0.0316]],

         [[ 0.7264],
          [ 0.2372],
          [ 0.4440],
          [ 0.0770]]],


        [[[ 0.3077],
          [ 0.2849],
          [ 0.7747],
          [ 0.1856]],

         [[ 0.0874],
          [ 0.2421],
          [ 0.9956],
          [ 0.9471]],

         [[ 0.5775],
          [ 0.4440],
          [ 0.6023],
          [ 0.4377]]]])
tensor([[[ 0.2525]],

        [[ 0.8433]]])
*** TODO: uncomment the lines and you will get error


# Inplace operations 

In [278]:
# Tensor to numpy related details
x = torch.rand((3,3), dtype = torch.float64)
x_np = x.numpy() 
print x_np, x_np.dtype

print '\nIn place addition to torch tensor'
x.add_(1) # if x is modified in place, numpy array also changes as it points to same location
print x_np

print '\nNormal addition'
x = x + 1 # if x is NOT modified in place, numpy array doesnt change
print x_np

[[0.84665304 0.95385044 0.71751871]
 [0.54830367 0.50653871 0.99209744]
 [0.85470537 0.08201796 0.0326165 ]] float64

In place addition to torch tensor
[[1.84665304 1.95385044 1.71751871]
 [1.54830367 1.50653871 1.99209744]
 [1.85470537 1.08201796 1.0326165 ]]

Normal addition
[[1.84665304 1.95385044 1.71751871]
 [1.54830367 1.50653871 1.99209744]
 [1.85470537 1.08201796 1.0326165 ]]


In [279]:
# Numpy to tensor related details
import numpy as np
a = np.ones((1,5), dtype = np.float64)
b = torch.from_numpy(a)
print(a)
print(b)

print '\nIn place addition to numpy array'
np.add(a, 1, out=a)
print(a)
print(b)

print '\nNormal addition'
a = a+1
print(a)
print(b)

[[1. 1. 1. 1. 1.]]
tensor([[ 1.,  1.,  1.,  1.,  1.]], dtype=torch.float64)

In place addition to numpy array
[[2. 2. 2. 2. 2.]]
tensor([[ 2.,  2.,  2.,  2.,  2.]], dtype=torch.float64)

Normal addition
[[3. 3. 3. 3. 3.]]
tensor([[ 2.,  2.,  2.,  2.,  2.]], dtype=torch.float64)


# CPU - GPU Transfer

In [320]:
if torch.cuda.is_available():
    device = torch.device("cuda")          # a CUDA device object : uses default cuda device
    device_gpu0 = torch.device("cuda:0")   # Uses gpu 0(indexed from 0)
    print device
    x = torch.rand((3,3))     #non cuda tensor
    x = x.to(device)          #converts non cuda to cuda and loads on default gpu
    y = torch.tensor([1,2]).cuda() #converts non cuda to cuda and loads on default gpu
    
    u = torch.ones((3,3), device=device_gpu0) # loads on GPU 0
    v = torch.ones((3,3), device=device_gpu0) # loads on GPU 0
    
    with torch.cuda.device(1): #loads the following lines on GPU 1 
        a = torch.tensor([1., 2.]).cuda() # loads on GPU 1 irrespective of default GPU
        b = torch.tensor([1., 2.]).cuda() # loads on GPU 1 irrespective of default GPU
        c = a + b # stored on GPU 1 irrespective of default GPU
        
        w = u + v # stored on GPU 0 because u and v belong to gpu 0
        z = a + u # Raises error as the two variables are on different GPU
else:
    print 'Cuda support not available'
    
print '\n\n***Once a tensor is allocated, you can do operations on it irrespective of the selected device, \
and the results will be always placed in on the same device as the tensor.'
    
print '\n\n*** Cross-GPU operations are not allowed by default, with the exception of copy_() \
and other methods with copy-like functionality such as to() and cuda(). '
print 'Any attempts to launch ops on tensors spread across different devices will raise an error.'

Cuda support not available


***Once a tensor is allocated, you can do operations on it irrespective of the selected device, and the results will be always placed in on the same device as the tensor.


*** Cross-GPU operations are not allowed by default, with the exception of copy_() and other methods with copy-like functionality such as to() and cuda(). 
Any attempts to launch ops on tensors spread across different devices will raise an error.


In [281]:
#to convert a tensor to cpu
if torch.cuda.is_available():
    device = torch.device("cuda")
    y = torch.ones((3,3), device=device)
    z = y.to('cpu')
    x = y.cpu()
    # Alternatively
    device_cpu = torch.device('cpu')
    z = y.to(device_cpu)

# Autograd Package

In [282]:
# Autograd Package
# torch.Tensor is the central class of the package. 
# If you set its attribute .requires_grad as True, it starts to track all operations on it.
x = torch.ones(2, 2, requires_grad=True)
print(x)

#Tensor and Function are interconnected and build up an acyclic graph, 
# that encodes a complete history of computation.

# Each variable has a .grad_fn attribute that references a Function that has created the Tensor 
# (except for Tensors created by the user - their grad_fn is None).
y = x + 2
z = y * y * 3
out = z.mean()
print('x.requires_grad:', x.requires_grad)
print('y.requires_grad:', y.requires_grad)
print('z.requires_grad:', z.requires_grad)
print('out.requires_grad:', out.requires_grad)
print('Grad fn of x:', x.grad_fn)
print('Grad fn of y:', y.grad_fn)
print('Grad fn of z:', z.grad_fn)
print('Grad fn of out:', out.grad_fn)



def print_gradFn(parent_fn):
    print(parent_fn , '-->')
    if parent_fn is not None and len(parent_fn.next_functions)>0:
        for i in range(len(parent_fn.next_functions)):
            print_gradFn(parent_fn.next_functions[i][0])
    else:
        print('-------')
    
print('\n\nVisualize the chain:')    
print_gradFn(out.grad_fn)

print('\n\n***TODO: Now set requires_grad of x to ' +  str(not x.requires_grad) + ' and check what happens')


tensor([[ 1.,  1.],
        [ 1.,  1.]])
('x.requires_grad:', True)
('y.requires_grad:', True)
('z.requires_grad:', True)
('out.requires_grad:', True)
('Grad fn of x:', None)
('Grad fn of y:', <AddBackward0 object at 0x7f622e5abbd0>)
('Grad fn of z:', <MulBackward0 object at 0x7f622e5abd50>)
('Grad fn of out:', <MeanBackward1 object at 0x7f622e5abbd0>)


Visualize the chain:
(<MeanBackward1 object at 0x7f622d6db950>, '-->')
(<MulBackward0 object at 0x7f622e649150>, '-->')
(<MulBackward1 object at 0x7f622e6491d0>, '-->')
(<AddBackward0 object at 0x7f622e649110>, '-->')
(<AccumulateGrad object at 0x7f622e649250>, '-->')
-------
(<AddBackward0 object at 0x7f622e649110>, '-->')
(<AccumulateGrad object at 0x7f622e649250>, '-->')
-------


***TODO: Now set requires_grad of x to False and check what happens


In [283]:
# To prevent tracking history (and using memory), you can also wrap the code block in with torch.no_grad():. 
# This can be particularly helpful when evaluating a model because the model may have trainable parameters 
# with requires_grad=True, but we don’t need the gradients.
print ('y.requires_grad:', y.requires_grad)
with torch.no_grad():
    y_mean1 = y.mean() # doesnt add to computational graph
print ('y_mean1.requires_grad:', y_mean1.requires_grad)    

y_mean2 = y.mean() # adds to computational graph
y_mean2_sq = y_mean2 * y_mean2 # gradient is tracked
print ('y_mean2.requires_grad:', y_mean2.requires_grad)
print ('y_mean2_sq.requires_grad:', y_mean2_sq.requires_grad)



('y.requires_grad:', True)
('y_mean1.requires_grad:', False)
('y_mean2.requires_grad:', True)
('y_mean2_sq.requires_grad:', True)


In [284]:
# To stop a tensor from tracking history, you can call .detach() to detach it from the computation history, 
# and to prevent future computation from being tracked.
y_mean3 = y.detach().mean() # detaches from computational graph for computation of y_mean3
y_mean3_sq = y_mean3 * y_mean3 # gradient is tracked
print ('y.requires_grad:', y.requires_grad)
print ('y_mean3.requires_grad:', y_mean3.requires_grad)
print ('y_mean3_sq.requires_grad:', y_mean3_sq.requires_grad)

('y.requires_grad:', True)
('y_mean3.requires_grad:', False)
('y_mean3_sq.requires_grad:', False)


In [285]:
# The gradient for this tensor will be accumulated into .grad attribute.
print('x grad:', x.grad)
print('y grad:', y.grad)
print('z grad:', z.grad)
print('out grad:', out.grad)
print('x.requires_grad:', x.requires_grad)
print('y.requires_grad:', y.requires_grad)
print('z.requires_grad:', z.requires_grad)
print('out.requires_grad:', out.requires_grad)
# If you want to compute the derivatives, you can call .backward() on a Tensor
# When you finish your computation you can call .backward() and have all the gradients computed automatically. 
out.backward()
print('\n\n***TODO: Compute the derivative by hand and plug in the value of x and see if it matches\n')
print('x grad:', x.grad)
print('y grad:', y.grad)
print('z grad:', z.grad)
print('out grad:', out.grad)



('x grad:', None)
('y grad:', None)
('z grad:', None)
('out grad:', None)
('x.requires_grad:', True)
('y.requires_grad:', True)
('z.requires_grad:', True)
('out.requires_grad:', True)


***TODO: Compute the derivative by hand and plug in the value of x and see if it matches

('x grad:', tensor([[ 4.5000,  4.5000],
        [ 4.5000,  4.5000]]))
('y grad:', None)
('z grad:', None)
('out grad:', None)


In [ ]:
x = torch.randn(3, 4)
print x


# Some Important functions

In [326]:
# squeeze removes all dimensions of size 1
x = torch.rand((3,1,4,5,1,6))
print 'x.size before squeezing: ', x.size()
x = x.squeeze()
print 'x.size after squeezing : ', x.size()


x.size before squeezing:  torch.Size([3, 1, 4, 5, 1, 6])
x.size after squeezing :  torch.Size([3, 4, 5, 6])


In [356]:
# torch.cat concatenates two tensors in a given dimension
w = torch.rand(64,3,2)
x = torch.rand(128,3,2)
print 'w.size: ', w.size()
print 'x.size: ', x.size()

y = torch.cat((w,x), 0)
print 'w,x concatenated along dim 0: ', y.size()
print '***Example could be you have 2 set of feature maps and you want to combine them,\
then concatinate along the channel dimension'
print '*** All other dims must be of same size. The concat dim may have different size'

w.size:  torch.Size([64, 3, 2])
x.size:  torch.Size([128, 3, 2])
w,x concatenated along dim 0:  torch.Size([192, 3, 2])
***Example could be you have 2 set of feature maps and you want to combine them,then concatinate along the channel dimension
*** All other dims must be of same size. The concat dim may have different size


In [359]:
# torch.stack concatenates two tensors along a new dimension
w = torch.rand(3,5,4)
x = torch.rand(3,5,4)
print 'w.size: ', w.size()
print 'x.size: ', x.size()

z = torch.stack((w,x), 1)
print 'z.size: ', z.size()
print '***Example could be you have 5 different images and you want to create a batch. then stack along dim 0'
print '***All the dims must be of same size.'
print '***TODO: compare with torch.cat and see the difference'

w.size:  torch.Size([3, 5, 4])
x.size:  torch.Size([3, 5, 4])
z.size:  torch.Size([3, 2, 5, 4])
***Example could be you have 5 different images and you want to create a batch. then stack along dim 0
***All the dims must be of same size.
***TODO: compare with torch.cat and see the difference


In [368]:
# torch.unsqueeze adds a new dimension at specified dim
x = torch.rand(3,4,5)
y = torch.unsqueeze(x,1)

print 'x.size: ', x.size()
print 'y.size: ', y.size()
print '***Example you have gray channel images stacked to form a batch, but we need to add an empty dimension of size 1 as above'

x.size:  torch.Size([3, 4, 5])
y.size:  torch.Size([3, 1, 4, 5])
***Example you have gray channel images stacked to form a batch, but we need to add an empty dimension of size 1 as above


In [371]:
#torch.where(cond, t1, t2) takes in a condition and returns the values from first tensor if condition is true, 
# else returns from tensor 2
x = torch.FloatTensor([0, 155, 183, 65, 270, 33, 125, 300, 35, 21])
torch.where(x > 180, x-360, x)

print '***Example you have angles between 0 to 360 and you want to convert into -180 to 180 '

tensor([   0.,  155., -177.,   65.,  -90.,   33.,  125.,  -60.,   35.,
          21.])

In [373]:
# torch.argmax and torch.max
a = torch.randn(4,4)
print a
print torch.argmax(a, dim=1)
maxVal, maxInd = torch.max(a,dim=1)
print maxVal, maxInd

tensor([[-0.0738,  0.1720,  0.9996, -0.9688],
        [-0.6914, -0.3050, -0.9588, -2.1365],
        [ 0.7953, -0.5974, -1.6095, -0.4417],
        [-0.0047, -1.9251, -0.0936,  0.7265]])
tensor([ 2,  1,  0,  3])
tensor([ 0.9996, -0.3050,  0.7953,  0.7265]) tensor([ 2,  1,  0,  3])
